services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    command: "uvicorn --factory presentation.api.main:get_litestar_app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - ../.env
    volumes:
      - ../src/:/src/
    networks:
      - backend

networks:
  backend:
    driver: bridge
